Repository dhairyagothi/StationGuide, pull requests merged in 2024-10, with the labels that each got.

#22 Create contribution.md
  contribution.md
Labels: documentation, Level 1, gssoc-ext, hacktoberfest-accepted

#26 Added contributors logo on README
  README.md
Labels: documentation, Level 1, gssoc-ext, hacktoberfest-accepted

#27 Update StationGuide Chatbot figma
  StationGuideFigma.md
Labels: documentation, enhancement, Level 1, gssoc-ext, hacktoberfest-accepted

#29 Create Learn.md
  Learn.md
Labels: Level 1, gssoc-ext, hacktoberfest-accepted

#24 Created Signup, login, logout, and verifyToken Routes in Backend
  .gitignore
  backend/config/config.js
  backend/config/dbConnection.js
  backend/controllers/authController.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  backend/utils/authFunctions.js
Labels: dependencies, Level 3, gssoc-ext, hacktoberfest-accepted

#30 Added "Already have an account then login" link to Signup page and vice versa
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, Level 1, gssoc-ext, hacktoberfest-accepted

#37 Fixed hamburger menu ,colour, search icon, greeting phrase
  frontend/src/Pages/Herosection.css
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/hamburger.jsx
Labels: enhancement, Level 2, gssoc-ext, hacktoberfest-accepted

#39 Changes for contributors information
  .all-contributorsrc
  .github/workflows/add-contributors.yml
  .github/workflows/all-contributors-auto-comment.yml
  .github/workflows/autocomment.yaml
  README.md
  frontend/src/Pages/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#40 COMMUNITY STANDARS UPDATED
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: hacktoberfest-accepted

#42 Updated the Navbar and the package.json for adding react-scripts start
  frontend/package.json
  frontend/src/Pages/hamburger.jsx
Labels: enhancement, Level 2, gssoc-ext, hacktoberfest-accepted

#43 Integrated backend with frontend login and register functionality
  backend/config/config.js
  backend/package.json
  backend/utils/authFunctions.js
  frontend/src/App.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: Level 2, gssoc-ext, hacktoberfest-accepted

#54 Improve the UI of the Login and Register Page
  frontend/src/Pages/Herosection.css
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
  frontend/src/Pages/hamburger.css
  frontend/src/Pages/hamburger.jsx
  frontend/src/Pages/navigation.jsx
Labels: enhancement, Level 2, gssoc-ext, hacktoberfest-accepted

#56 Readme file and code of conduct enhancement
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, Level 1, gssoc-ext, hacktoberfest-accepted

#57 hacktoberfest
  .all-contributorsrc
  README.md
  frontend/.gitignore
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/Pages/Herosection.jsx
Labels: hacktoberfest-accepted

#58 MultiLangauge Facility
  frontend/index.html
Labels: documentation, Level 2, gssoc-ext, hacktoberfest-accepted

#55 Changed the Icons according to the suitable format on the frontend
  frontend/package-lock.json
  frontend/src/Pages/Herosection.jsx
Labels: enhancement, Level 2, gssoc-ext, hacktoberfest-accepted

#67 routes update
  frontend/src/App.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: documentation, enhancement, gssoc-ext, hacktoberfest-accepted

#76 Adding Chatbot
  frontend/index.html
  package-lock.json
  package.json
Labels: dependencies, Level 3, gssoc-ext, hacktoberfest-accepted

#89 Added a Custom Cursor Effect
  frontend/index.html
Labels: enhancement, good first issue, Level 1, gssoc-ext, hacktoberfest-accepted

#100 Fixed Alignment of the herosection
  frontend/index.html
  frontend/src/App.jsx
Labels: enhancement, Level 1, gssoc-ext, hacktoberfest-accepted

#102 contributors
  frontend/src/Pages/Herosection.jsx
  frontend/src/assets/svg/contributor.svg
Labels: hacktoberfest-accepted

#111 Checking 10-digit phone number has been implimented
  frontend/src/Pages/Register.jsx
Labels: good first issue, Level 1, gssoc-ext, hacktoberfest-accepted

#106 add stations page
  frontend/src/App.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/stations.jsx
  package-lock.json
  package.json
Labels: Level 3, gssoc-ext, hacktoberfest-accepted

#117 svg image fixed
  frontend/src/assets/stationsaarthi.svg
Labels: Level 1, gssoc-ext, hacktoberfest-accepted

#118 Routes update
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: bug, enhancement, Level 1, gssoc-ext, hacktoberfest-accepted

#123 login feature redirect done
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
  frontend/src/assets/svg/backicon.svg
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#122 Add more Buttons in the Landing Page and add a new station . In Next Pr i will make navigate for every button by making some new routes
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/stations.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#130 Station search page 2.0
  frontend/src/Pages/stations.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#107 Added cloakroom and wheelchair booking backend routes
  backend/controllers/WheelchairController.js
  backend/controllers/cloakroomController.js
  backend/controllers/coolieController.js
  backend/index.js
  backend/models/CloakroomBooking.js
  backend/models/CoolieBooking.js
  backend/models/WheelchairBooking.js
  backend/routes/authRoutes.js
Labels: dependencies, level 3, gssoc-ext, hacktoberfest-accepted

#125 Readme Updation
  README.md
Labels: documentation, enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#146 whitish background fixed
  frontend/src/Pages/Herosection.css
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#132 #issue 120 Add Docker Setup for Frontend and Backend
  backend/.dockerignore
  backend/config/config.js
  backend/dockerfile
  backend/package-lock.json
  docker-compose.yml
  frontend/.dockerignore
  frontend/dockerfile
  frontend/vite.config.js
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#148 Added back button on station page
  frontend/src/Pages/Register.jsx
  frontend/src/Pages/stations.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#154 Added state-wise filter to the station page
  frontend/src/Pages/stations.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#156 Confirmation msg upon registering
  frontend/src/Pages/Register.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#147 In this Pr i made all the routes necessary from the landing page , and add some code in the new pages that were empty for initial period , and i made half of the buttons go to their respective routes
  frontend/src/App.jsx
  frontend/src/Pages/3Dmaps.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/booking.jsx
  frontend/src/Pages/contributor.jsx
  frontend/src/Pages/navigation.jsx
  frontend/src/Pages/notification.jsx
  frontend/src/Pages/schedule.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#160 Routes Updated
  frontend/src/App.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/booking.jsx
  frontend/src/Pages/contributor.jsx
  frontend/src/Pages/notification.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#149 Eye icon added in register and login page issue #137
  frontend/package-lock.json
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#165 removed unused dep issue #150
  backend/package-lock.json
  backend/package.json
Labels: dependencies, level 1, gssoc-ext, hacktoberfest-accepted

#172 fixed backicon
  frontend/src/Pages/stations.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#163 add contact us page 1.0
  frontend/src/App.jsx
  frontend/src/Pages/ContactUs.jsx
  frontend/src/Pages/hamburger.jsx
Labels: enhancement, level 3, gssoc-ext, Hacktoberfest

#175 Chatbot routes and css fix
  frontend/index.html
  frontend/src/Pages/Herosection.jsx
  frontend/src/components/chatbot.css
  frontend/src/components/chatbot.jsx
Labels: level 3, gssoc-ext, hacktoberfest-accepted

#174 Added Station Schema : Fixes issue #159
  backend/models/Stations.js
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#176 Update booking.jsx
  frontend/src/Pages/booking.jsx
Labels: level 3, gssoc-ext, hacktoberfest-accepted

#184 Hamburger Route updated
  frontend/src/App.jsx
  frontend/src/Pages/hamburger.jsx
  frontend/src/components/Settings.jsx
  frontend/src/components/about.jsx
  frontend/src/components/hamburger.jsx
  frontend/src/components/help.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#179 Added the contributors page and properly designed it.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Herosection.css
  frontend/src/Pages/contributor.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#183 Add handle register functionality
  backend/package-lock.json
  backend/package.json
  frontend/src/Pages/Register.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#194 Login Successful
  frontend/src/Pages/LoginPage.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#206 Fixed the postion of the arrow
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, good first issue, level 1, gssoc-ext, hacktoberfest-accepted

#204 Added the OAuth for Google on signup Page
  backend/controllers/authController.js
  backend/models/User.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Register.jsx
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#207 Added About Us page
  frontend/package-lock.json
  frontend/src/components/about.css
  frontend/src/components/about.jsx
Labels: enhancement, good first issue, level 2, gssoc-ext, hacktoberfest-accepted

#219 added new global font
  frontend/index.html
  frontend/src/App.css
  frontend/src/Pages/Herosection.jsx
  frontend/src/index.css
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#210 improved input search
  frontend/src/Pages/hamburger.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#222 Adding back icon in contributors and contact us page
  frontend/src/Pages/ContactUs.jsx
  frontend/src/Pages/contributor.jsx
Labels: enhancement, good first issue, level 2, gssoc-ext, hacktoberfest-accepted

#220 Step 1 of making the structure of the Navigation Page Completed
  frontend/src/Pages/navigation.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#227 Update notification.jsx
  frontend/src/Pages/notification.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#224 Added scroll to top button
  frontend/src/components/scrollToTop.css
  frontend/src/components/scrollToTop.jsx
  frontend/src/main.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#228 Added station services
  backend/controllers/StationController.js
  backend/controllers/WheelchairController.js
  backend/controllers/stationBookingsController.js
  backend/index.js
  backend/models/CloakroomBooking.js
  backend/models/CoolieBooking.js
  backend/models/Stations.js
  backend/models/WheelchairBooking.js
  backend/routes/stationRoutes.js
  frontend/package-lock.json
  frontend/src/App.jsx
  frontend/src/Pages/booking.jsx
  frontend/src/components/Bookingform.jsx
Labels: level 3, gssoc-ext, hacktoberfest-accepted

#230 Added theme to ScrollBar !!
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  package-lock.json
  package.json
  tailwind.config.js
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#240 Add Navigation Page with Current Location and Map Integration
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/navigation.jsx
  frontend/src/components/MapComponent.jsx
Labels: dependencies, level 3, gssoc-ext, hacktoberfest-accepted

#237 form validation added
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
  frontend/src/validations/validation.js
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#231 Added Mini Calendar in Bookingpage
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/booking.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#208 Feature : Implemented responsive Navbar with hamburger menu for mobil…
  frontend/src/Pages/Herosection.jsx
  frontend/src/components/navbar.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#232 Title bar Added for all the pages
  frontend/src/Pages/3Dmaps.jsx
  frontend/src/Pages/ContactUs.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
  frontend/src/Pages/contributor.jsx
  frontend/src/Pages/navigation.jsx
  frontend/src/Pages/notification.jsx
  frontend/src/Pages/schedule.jsx
  frontend/src/Pages/stations.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#229 [feat] : Improved Register.jsx file
  frontend/src/Pages/Register.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#246 added middleware
  backend/middleware/auth.middleware.js
  backend/routes/authRoutes.js
  backend/utils/ApiError.js
  backend/utils/asyncHandler.js
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#255 Step 3: Improve Location Detection and Map Centering on Current Location
  frontend/src/components/MapComponent.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#261 fixed cursor effects
  frontend/index.html
Labels: good first issue, level 2, gssoc-ext, hacktoberfest-accepted

#253 stationcode
  frontend/src/Pages/stations.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#264 solved issue #238
  frontend/index.html
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted

#245 Update schedule.jsx
  frontend/src/Pages/schedule.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#276 Feat: Automate the Project structure section
  .github/scripts/update_structure.py
  .github/workflows/Update-README.yml
  README.md
  repo_structure.txt
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#289 PR for issue #263
  frontend/src/Pages/Herosection.jsx
  frontend/src/components/chatbot.css
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#296 Navbar button Routes and Pages.
  README.md
  frontend/src/App.jsx
  frontend/src/Pages/AboutUs.jsx
  frontend/src/Pages/Emergency.jsx
  frontend/src/Pages/ForaFriend.jsx
  frontend/src/Pages/HelpandSupport.jsx
  frontend/src/Pages/Payment.jsx
  frontend/src/components/navbar.jsx
  repo_structure.txt
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#294 Update navigation.jsx
  frontend/src/Pages/navigation.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#292 Update booking.jsx
  frontend/src/Pages/booking.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#300 Updated chatbot close button
  frontend/src/components/chatbot.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#301 Done some enhancements and also added some new sections
  CONTRIBUTING.md
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#309 Add 'rate us' model in Hamburger.
  frontend/src/components/navbar.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#317 Fix Signup/Regiter Errors
  frontend/src/Pages/Register.jsx
  frontend/src/Pages/stations.jsx
  frontend/src/validations/validation.js
Labels: dependencies, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#319 fixed colors in hamburger
  frontend/index.html
  frontend/src/Pages/Emergency.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/Payment.jsx
  frontend/src/components/about.jsx
  frontend/src/components/navbar.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#314 Create a Payment Page - Debit,Credit, Apple pay, Google pay
  frontend/src/Pages/Emergency.jsx
  frontend/src/Pages/Payment.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#297 fix: overlapping
  frontend/src/components/scrollToTop.css
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#327 Main
  notification_system/backend/config/db.js
  notification_system/backend/controllers/notificationController.js
  notification_system/backend/models/Notification.js
  notification_system/backend/models/User.js
  notification_system/backend/package.json
  notification_system/backend/routes/notificationRoutes.js
  notification_system/backend/routes/userRoutes.js
  notification_system/backend/server.js
  notification_system/backend/services/emailServices.js
  notification_system/frontend/package.json
  notification_system/frontend/public/service-worker.js
  notification_system/frontend/src/app.js
  notification_system/frontend/src/components/NotificationCentre.js
  notification_system/frontend/src/components/NotificationSettings.js
  notification_system/frontend/src/index.js
Labels: documentation, dependencies, level 3, gssoc-ext, hacktoberfest-accepted

#328 language content overlapping corrected : #326 done
  frontend/index.html
  frontend/src/Pages/booking.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#333 Issue 322
  frontend/src/App.jsx
  frontend/src/Pages/HelpandSupport.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#344 payment page update
  frontend/src/Pages/Payment.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted

#336 Add feedback/Rate us
  backend/controllers/authController.js
  backend/controllers/submitFeedback.js
  backend/middleware/auth.middleware.js
  backend/models/User.js
  backend/routes/authRoutes.js
  frontend/src/Pages/Register.jsx
  frontend/src/components/navbar.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#348 Added Error Page To website
  frontend/src/App.jsx
  frontend/src/Pages/Error.jsx
  frontend/src/assets/StatioSarthi-error-404.png
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#358 changes in mobile view
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/hamburger.jsx
  frontend/src/components/navbar.jsx
Labels: good first issue, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#367 backicon and routes updated
  frontend/index.html
  frontend/src/Pages/3Dmaps.jsx
  frontend/src/Pages/Emergency.jsx
  frontend/src/Pages/HelpandSupport.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Payment.jsx
  frontend/src/Pages/Register.jsx
  frontend/src/Pages/stations.jsx
  frontend/src/components/Settings.jsx
  frontend/src/components/about.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#360 removed unrequired files
  frontend/src/Pages/3Dmaps.jsx
  frontend/src/Pages/ForaFriend.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/hamburger.css
  frontend/src/components/Bookingform.jsx
  frontend/src/components/footer.jsx
  frontend/src/components/help.jsx
Labels: enhancement, good first issue, level 1, gssoc-ext, hacktoberfest-accepted

#373 Added icons in register and login page
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#371 Mouse pointer bug fixed
  frontend/index.html
Labels: enhancement, good first issue, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#361 Station/popup
  frontend/index.html
  frontend/src/assets/railways.png
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#351 Issue no. 321- Update Emergency.jsx
  frontend/src/Pages/Emergency.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#380 Fixed animated cursor
  frontend/index.html
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#386 Fixed preloader
  frontend/index.html
Labels: level 2, gssoc-ext, hacktoberfest-accepted

#387 fixed languagebox
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Herosection.jsx
  frontend/src/components/language.css
  frontend/src/components/language.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#391 integrated userpage
  frontend/src/App.jsx
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/User.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted

#394 Enhancement: Add Dropdown for Coach Class in Train Schedule Page
  frontend/src/Pages/schedule.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#397 🛠️Fix : Calendar Date Validation: Allows Selection of Past Dates
  frontend/src/Pages/booking.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#395 Password-Recovery-Feature
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/PasswordRecovery.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#409 Fixed popup
  frontend/index.html
  frontend/src/Pages/Herosection.jsx
  frontend/src/components/popup.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#411 Enhanced booking section
  frontend/src/Pages/booking.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#404 🛠️Fix : Calendar Date Validation: Allows Selection of Past Dates
  frontend/src/Pages/booking.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted

#408 Update README.md
  README.md
Labels: documentation, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#414 Fixed Schedule Page
  frontend/src/Pages/schedule.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#382 Add Privacy and Policy page with styling
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Pages/PrivacyPolicy.css
  frontend/src/Pages/PrivacyPolicy.jsx
  frontend/src/Pages/hamburger.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/navbar.jsx
Labels: level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#417 Added chatbot !!!
  frontend/index.html
Labels: level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#392 Add trains to the application
  backend/controllers/trainController.js
  backend/index.js
  backend/models/Trains.js
  backend/routes/trainRoutes.js
  frontend/src/Pages/schedule.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#418 reduced scroll bar width
  frontend/src/App.css
Labels: good first issue, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#422 Text space fixed.
  frontend/src/Pages/AboutUs.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#423 forgot password feature added backend and frontend : #325 done
  backend/.env.sample
  backend/controllers/submitFeedback.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  backend/routes/stationRoutes.js
  backend/utils/emailUtils.js
  backend/utils/otputils.js
  frontend/src/Pages/PasswordRecovery.jsx
Labels: level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#425 Update README.md
  README.md
Labels: documentation, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#427 add ContactUs Page
  backend/controllers/contactusController.js
  backend/index.js
  backend/routes/contactUsRouter.js
  frontend/src/Pages/ContactUs.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#439 Add functionality to Schedule Page
  frontend/package-lock.json
  frontend/src/Pages/schedule.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#443 Revamped About Us Page, Added cards and Carousel with dedicated Sections
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Pages/AboutUs.jsx
  frontend/src/components/TeamSection.jsx
  frontend/src/components/about.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#445 Login through Google
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Firebase.jsx
  frontend/src/Pages/LoginPage.jsx
Labels: enhancement, dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#451 Fixed overlapping of search bar and profile button
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/hamburger.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#453 clicking on home on contributor page go to the home page : #446 done
  frontend/src/Pages/contributor.jsx
Labels: enhancement, good first issue, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#452 Updated the readme file
  README.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
  assets/image
Labels: enhancement, good first issue, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#459 Multi-Language Support Using Language Translator
  frontend/src/App.jsx
  frontend/src/Pages/GoogleTranslate.jsx
  frontend/src/Pages/Herosection.jsx
Labels: enhancement, dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#461 added rate limit middleware
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
Labels: dependencies, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#471 Language selector overlapping removed : #467 done
  frontend/src/components/navbar.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest
