Repository dhairyagothi/StationGuide, pull requests merged in 2024-11, with the labels that each got.

#481 Added Copyright at footer
  frontend/index.html
  frontend/src/components/navbar.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#485 ComplainBox Adding
  frontend/index.html
  frontend/package-lock.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Pages/ComplainBox.jsx
  frontend/src/components/navbar.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#484 The height of the homepage need to be adjusted (fixes #465)
  frontend/src/App.css
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#482 Offline First Experience with Caching and Sync Status Indicator
  frontend/package copy.json
  frontend/public/offline.html
  frontend/public/service-worker.js
  frontend/src/main.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#488 added:: Meta Tags, robots.txt, sitemaps for SEO Enhancement
  frontend/generate-sitemap.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/robots.txt
  frontend/public/sitemap.xml
  frontend/src/App.jsx
  frontend/src/metadata.jsx
Labels: enhancement, dependencies, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#495 added-settings
  frontend/src/components/Settings.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#496 Enhance Payment page and Change Alignment of Privacy and Policy
  frontend/src/Pages/Payment.jsx
  frontend/src/Pages/PrivacyPolicy.css
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#500 The back arrow in the Schedule page is fixed
  frontend/src/Pages/schedule.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#498 Dark Mode
  frontend/src/Pages/Herosection.jsx
  frontend/src/Pages/hamburger.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/components/navbar.jsx
  frontend/src/components/popup.jsx
  frontend/src/hooks/useDarkMode.js
  frontend/tailwind.config.js
Labels: enhancement, dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#487 stats section added on about us page.#476 done
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/AboutUs.jsx
  frontend/src/components/Stats.css
  frontend/src/components/Stats.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#499 Refactor Payment Page: Enhanced User Inputs and Validation Mechanisms
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Pages/Payment.jsx
Labels: enhancement, dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#503 Responsive sign-in and login with Google functions
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#504 the cursor animation is bugged #501
  frontend/index.html
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#505 Added FAQ Page Implementation for Improved User Support
  frontend/src/App.jsx
  frontend/src/Pages/Faq.css
  frontend/src/Pages/Faq.jsx
  frontend/src/Pages/hamburger.jsx
  frontend/src/components/navbar.jsx
Labels: enhancement, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#513 added back-to-top scroll up in readme
  README.md
Labels: documentation, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#516 Add complaints with email
  backend/.env.sample
  backend/controllers/complaintController.js
  backend/index.js
  backend/models/Complaint.js
  backend/package-lock.json
  backend/package.json
  backend/routes/complaintRoutes.js
  frontend/package-lock.json
  frontend/src/Pages/ComplainBox.jsx
  frontend/src/Pages/Register.jsx
Labels: enhancement, dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#519 improved email template
  backend/controllers/complaintController.js
  frontend/src/assets/station.png
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#520 Add stations pagination
  frontend/src/Pages/stations.jsx
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#517 forgot password link visible
  frontend/src/Pages/LoginPage.jsx
Labels: enhancement, level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#524 Implement "Contact Us" Page with Backend Email Integration
  backend/controllers/contactusController.js
  backend/models/Contact.js
  backend/routes/contactUsRouter.js
  frontend/src/Pages/Herosection.jsx
Labels: dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#525 resolved forgot password issues
  backend/controllers/submitFeedback.js
Labels: dependencies, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#526 Add email verification
  backend/controllers/authController.js
  backend/models/User.js
  backend/routes/authRoutes.js
Labels: dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#527 Cursor Follower Not Tracking Properly
  frontend/index.html
Labels: enhancement, level 2, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#530 🛠️Fix : Calendar Date Validation: Allows Selection of Past Dates
  frontend/src/Pages/booking.jsx
Labels: level 1, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#528 Add password Recovery
  backend/controllers/authController.js
  backend/routes/authRoutes.js
Labels: dependencies, level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#533 Add user profile page and API
  backend/controllers/userController.js
  backend/index.js
  backend/routes/userRoutes.js
  frontend/src/App.jsx
  frontend/src/Pages/Profile.jsx
  frontend/src/assets/person.jpg
Labels: level 3, gssoc-ext, hacktoberfest-accepted, hacktoberfest

#534 Contributor stats countup added #212
  frontend/src/Pages/contributor.jsx
Labels: level 2, gssoc-ext

#531 Add tickets availability
  backend/dataset/tickets.js
  backend/index.js
  backend/routes/ticketRoutes.js
  frontend/src/App.jsx
  frontend/src/Pages/TicketsAvailability.jsx
Labels: dependencies, level 3, gssoc-ext

#535 reviewfeedback pop up added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/navbar.jsx
Labels: level 3, gssoc-ext

#540 Add google login/signup
  backend/.env.sample
  backend/googleAuth.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/src/Pages/Register.jsx
Labels: enhancement, level 2, gssoc-ext

#541 added feedback form frontend + backend
  backend/controllers/complaintController.js
  backend/models/feedbackmodal.js
  backend/routes/complaintRoutes.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Pages/Feedback.jsx
Labels: level 3, gssoc-ext
